#include <sstream>
#include <string_view>
#include <utility>
#include <iostream>

#include "UEMeta/Cli.hpp"
#include "CLI/CLI.hpp"
#include "quill/Backend.h"
#include "quill/Frontend.h"
#include "quill/sinks/ConsoleSink.h"
#include "quill/sinks/FileSink.h"

/// @brief Validates that a CLI path names an existing non-empty file, optionally with a required filename.
static std::string ValidateFile(const std::string& path, const std::string& assertFileName = "") {
    std::error_code ec{};
    const UEMeta::StablePath temp{std::string_view{path}};
    if (!temp.Exists(ec)) {
        return fmtquill::format("File \"{}\" not found (OS returned error code {})", path, ec.value());
    }
    if (!temp.IsFile(ec)) {
        return fmtquill::format("File \"{}\" is not a regular file (OS returned error code {})", path, ec.value());
    }
    const auto file_size = std::filesystem::file_size(temp.UnderlyingPath(), ec);
    if (ec || !file_size) {
        return fmtquill::format("File \"{}\" is empty (OS returned error code {})", path, ec.value());
    }
    if (!assertFileName.empty() && temp.UnderlyingPath().filename().string() != assertFileName) {
        return fmtquill::format("File \"{}\" is not named \"{}\" (named '{}')!",
            path, assertFileName, temp.UnderlyingPath().filename().string());
    }
    return "";
}

/// @brief Returns the configured C++ translation unit path.
const UEMeta::StablePath& UEMeta::Config::CppPath() const {
    AssertInitialized();
    return cpp_path;
}

/// @brief Returns the configured compile_commands.json path.
const UEMeta::StablePath& UEMeta::Config::CcPath() const {
    AssertInitialized();
    return cc_path;
}

/// @brief Returns the configured Clang executable path.
const UEMeta::StablePath& UEMeta::Config::ClangPath() const {
    AssertInitialized();
    return clang_path;
}

/// @brief Returns arguments appended to the filtered compile command before invoking Clang.
const std::vector<std::string>& UEMeta::Config::AdditionalClangArgs() const {
    AssertInitialized();
    return additional_clang_args;
}

/// @brief Returns compile command arguments stripped before invoking Clang.
const std::vector<std::string>& UEMeta::Config::StripArgs() const {
    AssertInitialized();
    return strip_args;
}

/// @brief Returns the process-wide configuration singleton.
UEMeta::Config& UEMeta::Config::GetConfig() {
    static Config config{};
    return config;
}

/// @brief Throws if configuration access happens before CLI initialization succeeds.
void UEMeta::Config::AssertInitialized() const {
    if (initialized.test()) return;
    throw std::runtime_error("Tried to use Config before it was initialized!");
}

/// @brief Parses CLI arguments and commits validated values into the configuration singleton.
int UEMeta::Config::Initialize(int argc, char **argv) {
    auto& cfg = GetConfig();
    if (cfg.initialized.test()) {
        UEM_WARN("Tried to initialize an already initialized Config!");
        return 0;
    }

    CLI::App app{"Parses a translation unit in an Unreal project.", "UEMeta"};
    app.allow_windows_style_options();
    argv = app.ensure_utf8(argv);

    std::string cpp_path{};
    std::string cc_path{};
    std::string clang_path{};

    app.add_option("-f,--file", cpp_path, "Path of the cpp file that drives the translation unit to dump.")
        ->required()->check([](const auto& opt) -> std::string {
            return ValidateFile(opt);
        });

    app.add_option("-c,--compile-commands", cc_path, "Path of the compile_commands.json generated by UBT")
        ->required()->check([](const auto& opt) -> std::string {
            return ValidateFile(opt, "compile_commands.json");
        });

    auto opt_parse_as_linux = app.add_flag("-p,--parse-as-linux", cfg.no_cl,
        "Uses clang instead of clang-cl. Assumes that the --compile-commands is appropriate "
        "for clang. If --clang is given, this option may be ignored.");

    app.add_option("--clang", clang_path,
        "Path to the clang executable to use. If clang-cl is used, UEMeta will assume "
        "--compile-commands points to a MSVC-style build, otherwise if clang is used it will assume it points "
        "to a clang-style build. If not specified, it uses the bundled clang-cl executable, or the clang executable "
        "if --parse-as-linux is specified.")
        ->check(CLI::ExistingFile)->excludes(opt_parse_as_linux);

    app.add_option("--skip-loaded-args", cfg.strip_args,
        "Additional compile arguments to strip out of the compiler arguments loaded from compile_commands.json.\n"
        "PCH-related arguments are stripped out by necessity.\n"
        "For compiler arguments that have arguments themselves, you can append '{num_args}' to the argument to also strip"
        "out the next num_args tokens. So, '/I{1}' would strip out any instances of the /I argument followed by the"
        "token immediately after. Argument stripping happens before --additional-clang-args are appended.");

    app.add_option("--additional-clang-args", cfg.additional_clang_args,
        "Additional arguments to pass to the clang executable.");

    try {
        app.parse(argc, argv);
    } catch (const CLI::CallForHelp& ex) {
        app.exit(ex);
        return -1;
    } catch(const CLI::ParseError& ex) {
        return app.exit(ex);
    } catch (const std::exception& ex) {
        UEM_ERROR("CLI parse error: {}", ex.what());
        return -1;
    } catch (...) {
        UEM_ERROR("Unknown CLI parse error!");
        return -1;
    }

    try {
        cfg.cpp_path.Assign(std::string_view{cpp_path});
        cfg.cc_path.Assign(std::string_view{cc_path});

        if (clang_path.empty()) {
            cfg.clang_path.Assign(cfg.no_cl ? UEM_DEFAULT_CLANG_PATH : UEM_DEFAULT_CLANG_CL_PATH);
        } else {
            cfg.clang_path.Assign(std::string_view{clang_path});
        }

        if (const auto clang_error = ValidateFile(cfg.clang_path.string()); !clang_error.empty()) {
            return app.exit({"MissingClang",
                fmtquill::format("Resolved clang path '{}' is not a file!", cfg.clang_path.string()),
                CLI::ExitCodes::FileError});
        }

        cfg.strip_args.insert_range(cfg.strip_args.end(), UEM_DEFAULT_STRIP_LIST);
        cfg.additional_clang_args.emplace_back("/clang:-mwaitpkg");
        cfg.additional_clang_args.emplace_back("/clang:-fno-access-control");
        cfg.initialized.test_and_set();

        std::ostringstream config_stream;
        config_stream << cfg;
        UEM_INFO("Using config:\n{}", config_stream.str());
    } catch (const std::exception& ex) {
        UEM_ERROR("Config initialization failed after CLI parse: {}", ex.what());
        return -1;
    } catch (...) {
        UEM_ERROR("Config initialization failed after CLI parse with unknown exception");
        return -1;
    }
    return 0;
}

/// @brief Returns the initialized Quill logger, falling back to a bootstrap logger during early startup.
quill::Logger* UEMeta::Logger::GetQuill() const {
    if (logger) return logger;
    std::cerr << "using fallback logger" << std::endl;
    if (auto* fallback_logger = quill::Frontend::get_logger("uemeta_bootstrap")) {
        return fallback_logger;
    }
    quill::Backend::start();
    quill::ConsoleSinkConfig console_sink_config{};
    console_sink_config.set_stream("stderr");
    auto console_sink = quill::Frontend::create_or_get_sink<quill::ConsoleSink>(
        "uemeta_bootstrap_console", console_sink_config);
    return quill::Frontend::create_or_get_logger("uemeta_bootstrap", std::move(console_sink));
}

/// @brief Reports whether the main logger sink set has been installed.
bool UEMeta::Logger::IsInitialized() const {
    return !!logger;
}

/// @brief Returns the process-wide logger singleton.
UEMeta::Logger& UEMeta::Logger::GetLogger() {
    static Logger logger{};
    return logger;
}

/// @brief Throws if code requires the main logger before logger initialization succeeds.
void UEMeta::Logger::AssertInitialized() const {
    if (logger) return;
    throw std::runtime_error{"Tried to use Logger before it was initialized!."};
}

/// @brief Initializes Quill backend, console/file sinks, and the main logger.
int UEMeta::Logger::Initialize() {
    try {
        auto& logger = GetLogger();

        quill::Backend::start();
        quill::FileSinkConfig file_sink_config{};
        file_sink_config.set_filename_append_option(quill::FilenameAppendOption::StartDateTime);
        quill::ConsoleSinkConfig console_sink_config{};
        quill::ConsoleSinkConfig::Colours colours{};
        quill::PatternFormatterOptions formatter_options{};
        formatter_options.format_pattern = "%(time) [%(log_level)] %(message)";
        colours.assign_colour_to_log_level(quill::LogLevel::Info, quill::ConsoleSinkConfig::Colours::white);
        console_sink_config.set_colours(colours);
        console_sink_config.set_override_pattern_formatter_options(formatter_options);
        file_sink_config.set_override_pattern_formatter_options(formatter_options);
        auto console_sink = quill::Frontend::create_or_get_sink<quill::ConsoleSink>("console_main", console_sink_config);
        auto file_sink = quill::Frontend::create_or_get_sink<quill::FileSink>("uemeta.log", file_sink_config);

        if (!console_sink || !file_sink) {
            UEM_ERROR("Failed to initialize logger sinks.");
            return -1;
        }

        logger.logger = quill::Frontend::create_or_get_logger("main", {std::move(console_sink), std::move(file_sink)});

        if (!logger.logger) {
            UEM_ERROR("Failed to initialize logger.");
            return -1;
        }

        logger.logger->set_log_level(quill::LogLevel::TraceL1);
    } catch (const std::exception& ex) {
        UEM_ERROR("Failed to initialize logger with exception: {}", ex.what());
        return -1;
    } catch (...) {
        UEM_ERROR("Failed to initialize logger with unknown exception");
        return -1;
    }

    return 0;
}
