[parser-input]
; Path to compile_commands.json, or a JSON string representing the compile_commands.json.
; Can be supplied to command-line with --compile-commands or -c.
compile_commands =

; Use clang/clang.exe over or clang-cl/clang-cl.exe.
; If this is true, compile_commands must pass clang-compatible commands rather than MSVC-style commands.
prefer_clang = false

; Set the path to clang[-cl].exe to use instead of the bundled binaries.
; If this is set, then prefer_clang will be ignored.
clang_path =

; List of compile commands to ignore/strip from compile_commands.
; PCH related arguments are stripped out by necessity.
; For compiler arguments that have arguments themselves, you can append '{num_args}' to the argument to also strip
; out the next num_args tokens. So, '/I{1}' would strip out any instances of the /I argument followed by the
; token immediately after. Argument stripping happens before additional_clang_args are appended.
skip_commands =

; List of additional clang args to force into the command list passed to the resolved clang executable.
; /clang:-mwaitpkg and /clang:-fno-access-control forced to ignore common issues with parsing.
additional_clang_args =

[parser-output]
; Path to log file.
; If empty, no logs will be saved.
; If given, it should be relative to the directory of parser.exe, or absolute.
log = "parser.log"

; If given, all file paths in the generated files start at a path_begin item rather than the file system root.
; This is useful for stripping PII and eliminating parts of the path string that aren't needed.
; If a given path doesn't have a substring in the path_begin list, then the whole, absolute path is output.
path_begin =

; The path to the directory to save generated files in.
; Defaults to Output, next to parser.exe.
output_directory = ./Output

; The format of the generated files.
; If 'binary', then the data will be serialized according to protobuf's default implementation.
;   This is the smallest and fastest format to parse to and from.
; If 'json', then the data will be serialized as human-readable JSON.
;   Good for debugging.
output_format = json