Mode = parser_repl
# must be absolute or relative to this file
PathToParser = ../parser/out/parser.exe

[parser_repl]
Version =
OutDir =
ClangArgs =
Format =
LogLevel =

[merger_only]
InputDir =
OutputDir =

[parser_only]
Version =
PreferClang =
PreferFullNameInFileName =
Sync =
EnableUnrealExtensions =
Log =
FileDelimiter =
Output =
Format =
LogLevel =

# One of CompileCommands or AstFile should be given; if both are given, AstFile takes precedence
CompileCommands =
StripCommands =
AdditionalClangArgs =

AstFile =

[from_parser]
# Versions and AstFiles must be non-empty lists of the same length, where each version will be corresponded to each AST
# file.
Versions =
AstFiles =
Sync =
EnableUnrealExtensions =

[from_merger]
InputDir =