#include <map>
#include <format>
#include "UEMeta/Cli.hpp"
#include "CLI/CLI.hpp"

std::map<std::string, UEMeta::FileSplitStrategy> SSMap {
    {"Default", UEMeta::FileSplitStrategy::Default},
    {"ByClass", UEMeta::FileSplitStrategy::ByClass},
    {"ByParentDirectory", UEMeta::FileSplitStrategy::ByParentDirectory},
    {"ByFile", UEMeta::FileSplitStrategy::ByFile},
    {"Monofile", UEMeta::FileSplitStrategy::Monofile},
};

std::string validateFile(const std::string& path, const std::string& assertFileName = "") {
    const std::filesystem::path temp{path};
    std::error_code ec{};
    if (!std::filesystem::exists(temp, ec)) {
        return std::format("File \"{}\" not found (OS returned error code {}", path, ec.value());
    }
    if (!std::filesystem::is_regular_file(temp, ec)) {
        return std::format("File \"{}\" is not a regular file (OS returned error code {})", path, ec.value());
    }
    if (!std::filesystem::file_size(temp, ec)) {
        return std::format("File \"{}\" is empty (OS returned error code {})", path, ec.value());
    }
    if (!assertFileName.empty() && temp.filename() != assertFileName) {
        return std::format("File \"{}\" is not named \"{}\"!", path, assertFileName);
    }
    return "";
}

const std::filesystem::path& UEMeta::Config::CppPath() const {
    return cpp_path;
}

const std::filesystem::path& UEMeta::Config::CcPath() const {
    return cc_path;
}

const std::filesystem::path& UEMeta::Config::OutPath() const {
    return out_path;
}

const UEMeta::FileSplitStrategy& UEMeta::Config::SplitStrategy() const {
    return split_strategy;
}

const std::vector<std::filesystem::path>& UEMeta::Config::PdPaths() const {
    return pd_paths;
}

const std::filesystem::path & UEMeta::Config::ClangPath() const {
    return clang_path;
}

UEMeta::Config& UEMeta::Config::GetConfig() {
    static Config config{};
    return config;
}

int UEMeta::Config::Initialize(int argc, char **argv) {
    auto& cfg = GetConfig();

    CLI::App app{"Dumps a simplified AST of a translation unit in an Unreal project.", "UEMeta"};
    app.allow_windows_style_options();
    argv = app.ensure_utf8(argv);

    std::string async_error{};

    app.add_option("-f,--file", cfg.cpp_path, "Path of the cpp file that drives the translation unit to dump.")
        ->required()->check([](const auto& opt) -> std::string {
            return validateFile(opt);
        });

    app.add_option("-c,--compile-commands", cfg.cc_path, "Path of the compile_commands.json generated by UBT")
        ->required()->check([](const auto& opt) -> std::string {
            return validateFile(opt, "compile-commands.json");
        });

    auto opt_ss = app.add_option("--split-strategy", cfg.split_strategy,
        "How output JSONs should be generated:"
        "\n\t\t(Default) ByFile: Generates an AST JSON for every file."
        "\n\t\tByClass: Generates an AST JSON for every significant node (class, enum, struct, constants, free functions, etc)"
        "\n\t\tMonofile: Puts everything in a single JSON file."
        "\n\t\tByParentDirectory: All ASTs generated within directories given in the --parent-directories command go in the same file.")
            ->transform(CLI::CheckedTransformer(SSMap, CLI::ignore_case));

    auto opt_parent_dir = app.add_option("--parent-directories", cfg.pd_paths, "Space-separated list of directories to use as groups for ASTs within a JSON.")
        ->check(CLI::ExistingDirectory);

    app.callback([&] {
        cfg.cc_path.make_preferred();
        cfg.cpp_path.make_preferred();
        cfg.out_path.make_preferred();
        for (auto& pd_path : cfg.pd_paths) {
            pd_path.make_preferred();
        }
    });

    app.preparse_callback([&](...) {
        if (opt_ss->as<std::string>() == "ByParentDirectory") {
            opt_parent_dir->required();
            app.callback([&] {
                bool found_non_empty_file = false;
                for (const auto& parentPath : cfg.pd_paths) {
                    for (const auto& file : std::filesystem::recursive_directory_iterator{parentPath}) {
                        std::error_code ec;
                        if (!std::filesystem::is_regular_file(file, ec)) continue;
                        if (std::filesystem::file_size(file, ec)) {
                            found_non_empty_file = true;
                            break;
                        }
                    }
                    if (found_non_empty_file) break;
                }
                if (!found_non_empty_file) {
                    async_error = "Failed to find any non-empty files in the file trees of given --parent-directories!";
                }
            });
        }
    });

    app.add_option("-o,--out", cfg.out_path, "Directory to output JSON files to.")
        ->required()->check([](const auto& opt) -> std::string {
            const std::filesystem::path temp_path{opt};
            std::error_code ec{};

            if (std::filesystem::exists(temp_path, ec)) {
                if (!std::filesystem::is_directory(temp_path, ec)) {
                    return "Output path is not a directory!";
                }
                return "";
            }

            if (ec) {
                return std::format("Failed to check output directory existence: {}", ec.message());
            }

            if (!std::filesystem::create_directory(opt, ec)) {
                return std::format("Failed to create output directory: {}", ec.message());
            }

            return "";
        });

    auto opt_parse_as_linux = app.add_flag("-p,--parse-as-linux", cfg.no_cl,
        "Uses clang instead of clang-cl. Assumes that the --compile-commands is appropriate "
        "for clang. If --clang is given, this option may be ignored.");

    app.add_option("--clang", cfg.clang_path,
        "Path to the clang executable to use. If clang-cl is used, UEMeta will assume "
        "--compile-commands points to a MSVC-style build, otherwise if clang is used it will assume it points "
        "to a clang-style build. If not specified, it uses the bundled clang-cl executable, or the clang executable "
        "if --parse-as-linux is specified.")
        ->check(CLI::ExistingFile)->excludes(opt_parse_as_linux);

    try {
        app.parse(argc, argv);
    } catch (const CLI::CallForHelp& ex) {
        app.exit(ex);
        return -1;
    } catch(const CLI::ParseError& ex) {
        return app.exit(ex);
    } catch (const std::exception& ex) {
        std::cerr << "CLI parse error: " << ex.what() << std::endl;
        return -1;
    } catch (...) {
        std::cerr << "Unknown CLI parse error!" << std::endl;
        return -1;
    }

    if (!async_error.empty()) {
        return app.exit({"NoContentInParentDirectories", async_error, CLI::ExitCodes::FileError});
    }

    if (cfg.no_cl && cfg.clang_path.empty()) {
        cfg.clang_path = UEM_DEFAULT_CLANG_PATH;
    }

    std::cout << "Using config:\n" << cfg << std::endl;

    return 0;
}
