#include <map>
#include <format>
#include <string_view>
#include <utility>
#include "UEMeta/Cli.hpp"
#include "CLI/CLI.hpp"
#include "quill/Backend.h"
#include "quill/Frontend.h"
#include "quill/sinks/ConsoleSink.h"
#include "quill/sinks/FileSink.h"

std::map<std::string, UEMeta::FileSplitStrategy> SSMap {
    {"Default", UEMeta::FileSplitStrategy::Default},
    {"ByClass", UEMeta::FileSplitStrategy::ByClass},
    {"ByParentDirectory", UEMeta::FileSplitStrategy::ByParentDirectory},
    {"ByFile", UEMeta::FileSplitStrategy::ByFile},
    {"Monofile", UEMeta::FileSplitStrategy::Monofile},
};

std::string AssignStablePath(UEMeta::StablePath& out, const std::filesystem::path& path, const std::string_view label) {
    std::error_code ec{};
    out.Assign(path, ec);
    if (ec) {
        return std::format("Failed to stabilize {} path \"{}\": {}", label, path.string(), ec.message());
    }
    return "";
}

std::string AssignStablePath(UEMeta::StablePath& out, const std::string& path, const std::string_view label) {
    return AssignStablePath(out, std::filesystem::path{path}, label);
}

std::string ValidateFile(const std::string& path, const std::string& assertFileName = "") {
    std::error_code ec{};
    const UEMeta::StablePath temp{std::string_view{path}, ec};
    if (ec) {
        return std::format("Failed to stabilize file path \"{}\" (OS returned error code {})", path, ec.value());
    }
    if (!temp.Exists(ec)) {
        return std::format("File \"{}\" not found (OS returned error code {})", path, ec.value());
    }
    if (!temp.IsFile(ec)) {
        return std::format("File \"{}\" is not a regular file (OS returned error code {})", path, ec.value());
    }
    const auto file_size = std::filesystem::file_size(temp.UnderlyingPath(), ec);
    if (ec || !file_size) {
        return std::format("File \"{}\" is empty (OS returned error code {})", path, ec.value());
    }
    if (!assertFileName.empty() && temp.UnderlyingPath().filename().string() != assertFileName) {
        return std::format("File \"{}\" is not named \"{}\" (named '{}')!",
            path, assertFileName, temp.UnderlyingPath().filename().string());
    }
    return "";
}

const UEMeta::StablePath& UEMeta::Config::CppPath() const {
    AssertInitialized();
    return cpp_path;
}

const UEMeta::StablePath& UEMeta::Config::CcPath() const {
    AssertInitialized();
    return cc_path;
}

const UEMeta::StablePath& UEMeta::Config::OutPath() const {
    AssertInitialized();
    return out_path;
}

const UEMeta::FileSplitStrategy& UEMeta::Config::SplitStrategy() const {
    AssertInitialized();
    return split_strategy;
}

const std::vector<UEMeta::StablePath>& UEMeta::Config::PdPaths() const {
    AssertInitialized();
    return pd_paths;
}

const UEMeta::StablePath & UEMeta::Config::ClangPath() const {
    AssertInitialized();
    return clang_path;
}

const std::vector<std::string> & UEMeta::Config::AdditionalClangArgs() const {
    AssertInitialized();
    return additional_clang_args;
}

const std::vector<std::string> & UEMeta::Config::StripArgs() const {
    AssertInitialized();
    return strip_args;
}

UEMeta::Config& UEMeta::Config::GetConfig() {
    static Config config{};
    return config;
}

void UEMeta::Config::AssertInitialized() const {
    if (initialized.test()) return;
    throw std::runtime_error("Tried to use Config before it was initialized!");
}

int UEMeta::Config::Initialize(int argc, char **argv) {
    auto& cfg = GetConfig();
    if (cfg.initialized.test()) {
        UEM_WARN("Tried to initialize an already initialized Config!");
        return 0;
    }

    CLI::App app{"Dumps a simplified AST of a translation unit in an Unreal project.", "UEMeta"};
    app.allow_windows_style_options();
    argv = app.ensure_utf8(argv);

    std::string async_error{};
    std::string cpp_path{};
    std::string cc_path{};
    std::string out_path{};
    std::string clang_path{};
    std::vector<std::string> pd_paths{};

    app.add_option("-f,--file", cpp_path, "Path of the cpp file that drives the translation unit to dump.")
        ->required()->check([](const auto& opt) -> std::string {
            return ValidateFile(opt);
        });

    app.add_option("-c,--compile-commands", cc_path, "Path of the compile_commands.json generated by UBT")
        ->required()->check([](const auto& opt) -> std::string {
            return ValidateFile(opt, "compile_commands.json");
        });

    auto opt_ss = app.add_option("--split-strategy", cfg.split_strategy,
        "How output JSONs should be generated:"
        "\n\t\t(Default) ByFile: Generates an AST JSON for every file."
        "\n\t\tByClass: Generates an AST JSON for every significant node (class, enum, struct, constants, free functions, etc)"
        "\n\t\tMonofile: Puts everything in a single JSON file."
        "\n\t\tByParentDirectory: All ASTs generated within directories given in the --parent-directories command go in the same file.")
            ->transform(CLI::CheckedTransformer(SSMap, CLI::ignore_case));

    auto opt_parent_dir = app.add_option("--parent-directories", pd_paths, "Space-separated list of directories to use as groups for ASTs within a JSON.")
        ->check(CLI::ExistingDirectory);

    app.preparse_callback([&](...) {
        if (opt_ss->as<std::string>() == "ByParentDirectory") {
            opt_parent_dir->required();
        }
    });

    app.add_option("-o,--out", out_path, "Directory to output JSON files to.")
        ->required()->check([](const auto& opt) -> std::string {
            const std::filesystem::path temp_path{opt};
            std::error_code ec{};

            if (std::filesystem::exists(temp_path, ec)) {
                if (!std::filesystem::is_directory(temp_path, ec)) {
                    return "Output path is not a directory!";
                }
                return "";
            }

            if (ec) {
                return std::format("Failed to check output directory existence: {}", ec.message());
            }

            if (!std::filesystem::create_directory(opt, ec)) {
                return std::format("Failed to create output directory: {}", ec.message());
            }

            return "";
        });

    auto opt_parse_as_linux = app.add_flag("-p,--parse-as-linux", cfg.no_cl,
        "Uses clang instead of clang-cl. Assumes that the --compile-commands is appropriate "
        "for clang. If --clang is given, this option may be ignored.");

    app.add_option("--clang", clang_path,
        "Path to the clang executable to use. If clang-cl is used, UEMeta will assume "
        "--compile-commands points to a MSVC-style build, otherwise if clang is used it will assume it points "
        "to a clang-style build. If not specified, it uses the bundled clang-cl executable, or the clang executable "
        "if --parse-as-linux is specified.")
        ->check(CLI::ExistingFile)->excludes(opt_parse_as_linux);

    app.add_option("--skip-loaded-args", cfg.strip_args,
        "Additional compile arguments to strip out of the compiler arguments loaded from compile_commands.json.\n"
        "PCH-related arguments are stripped out by necessity.\n"
        "For compiler arguments that have arguments themselves, you can append '{num_args}' to the argument to also strip"
        "out the next num_args tokens. So, '/I{1}' would strip out any instances of the /I argument followed by the"
        "token immediately after. Argument stripping happens before --additional-clang-args are appended.");

    app.add_option("--additional-clang-args", cfg.additional_clang_args,
        "Additional arguments to pass to the clang executable.");

    app.add_option("--path-delimiters", cfg.path_delimiters,
        "Highest level roots allowed in paths in generated JSON files. "
        "If a path delimiter is found in a path in the JSON output, every directory/file above it is stripped from the path"
        "string. If multiple delimiters are found, the most specific root is chosen. "
        "This is for protecting PII when releasing JSONs publicly."
        "Defaults: 'Unreal', 'UnrealEngine', 'MetadataHarness' (forced)");

    app.add_option("--path-blacklist", cfg.path_blacklist,
        "Substrings to strip in paths in generated JSON files."
        "Found substrings will be replaced with the string 'blacklist'. "
        "This is for protecting PII when releasing JSONs publicly.");

    try {
        app.parse(argc, argv);
    } catch (const CLI::CallForHelp& ex) {
        app.exit(ex);
        return -1;
    } catch(const CLI::ParseError& ex) {
        return app.exit(ex);
    } catch (const std::exception& ex) {
        std::cerr << "CLI parse error: " << ex.what() << std::endl;
        return -1;
    } catch (...) {
        std::cerr << "Unknown CLI parse error!" << std::endl;
        return -1;
    }

    if (const auto error = AssignStablePath(cfg.cpp_path, cpp_path, "--file"); !error.empty()) {
        return app.exit({"InvalidFilePath", error, CLI::ExitCodes::FileError});
    }

    if (const auto error = AssignStablePath(cfg.cc_path, cc_path, "--compile-commands"); !error.empty()) {
        return app.exit({"InvalidCompileCommandsPath", error, CLI::ExitCodes::FileError});
    }

    if (const auto error = AssignStablePath(cfg.out_path, out_path, "--out"); !error.empty()) {
        return app.exit({"InvalidOutputPath", error, CLI::ExitCodes::FileError});
    }

    cfg.pd_paths.clear();
    cfg.pd_paths.reserve(pd_paths.size());
    for (const auto& pd_path : pd_paths) {
        StablePath stable_path{};
        if (const auto error = AssignStablePath(stable_path, pd_path, "--parent-directories"); !error.empty()) {
            return app.exit({"InvalidParentDirectoryPath", error, CLI::ExitCodes::FileError});
        }
        cfg.pd_paths.push_back(std::move(stable_path));
    }

    if (const auto error = clang_path.empty()
            ? AssignStablePath(cfg.clang_path, cfg.no_cl ? UEM_DEFAULT_CLANG_PATH : UEM_DEFAULT_CLANG_CL_PATH, "--clang")
            : AssignStablePath(cfg.clang_path, clang_path, "--clang");
        !error.empty()) {
        return app.exit({"InvalidClangPath", error, CLI::ExitCodes::FileError});
    }

    if (cfg.split_strategy == FileSplitStrategy::ByParentDirectory) {
        bool found_non_empty_file = false;
        for (const auto& parent_path : cfg.pd_paths) {
            std::error_code iterator_ec;
            for (std::filesystem::recursive_directory_iterator it{parent_path.UnderlyingPath(), iterator_ec}, end{};
                 it != end;
                 it.increment(iterator_ec)) {
                if (iterator_ec) {
                    iterator_ec.clear();
                    continue;
                }

                std::error_code file_ec;
                if (!it->is_regular_file(file_ec)) {
                    continue;
                }

                const auto size = it->file_size(file_ec);
                if (!file_ec && size) {
                    found_non_empty_file = true;
                    break;
                }
            }
            if (found_non_empty_file) break;
        }
        if (!found_non_empty_file) {
            async_error = "Failed to find any non-empty files in the file trees of given --parent-directories!";
        }
    }

    if (!async_error.empty()) {
        return app.exit({"NoContentInParentDirectories", async_error, CLI::ExitCodes::FileError});
    }

    if (!ValidateFile(cfg.clang_path.string()).empty()) {
        return app.exit({"MissingClang",
            std::format("Resolved clang path '{}' is not a file!", cfg.clang_path.string()),
            CLI::ExitCodes::FileError});
    }

    cfg.strip_args.insert_range(cfg.strip_args.end(), UEM_DEFAULT_STRIP_LIST);
    cfg.path_delimiters.emplace_back("MetadataHarness");
    cfg.initialized.test_and_set();

    std::cout << "Using config:\n" << cfg << std::endl;
    return 0;
}

quill::Logger* UEMeta::Logger::GetQuill() const {
    AssertInitialized();
    return logger;
}

bool UEMeta::Logger::IsInitialized() const {
    return !!logger;
}

UEMeta::Logger& UEMeta::Logger::GetLogger() {
    static Logger logger{};
    return logger;
}

void UEMeta::Logger::AssertInitialized() const {
    if (logger) return;
    throw std::runtime_error{"Tried to use Logger before it was initialized!."};
}

int UEMeta::Logger::Initialize() {
    try {
        auto& logger = GetLogger();

        quill::Backend::start();
        quill::FileSinkConfig file_sink_config{};
        file_sink_config.set_filename_append_option(quill::FilenameAppendOption::StartDateTime);
        auto console_sink = quill::Frontend::create_or_get_sink<quill::ConsoleSink>("console_main");
        auto file_sink = quill::Frontend::create_or_get_sink<quill::FileSink>("uemeta.log", file_sink_config);

        if (!console_sink || !file_sink)  return -1;

        logger.logger = quill::Frontend::create_or_get_logger("main", {std::move(console_sink), std::move(file_sink)});

        if (!logger.logger)  return -1;
    } catch (const std::exception& ex) {
        std::cerr << std::format("Failed to initialize logger with exception: {}", ex.what()) << std::endl;
        return -1;
    } catch (...) {
        std::cerr << std::format("Failed to initialize logger with unknown exception") << std::endl;
        return -1;
    }

    return 0;
}